management:
  info:
    env:
      enabled: true

server:
  port: 8080

info:
  build:
    version: "@project.version@"
spring:
  kafka:
    bootstrap-servers: localhost:49092
    consumer:
      properties:
        spring.json.value.default.type: com.brunobs.auth.messaging.dto.AccountCacheDTO
        spring.json.trusted.packages: com.brunobs.sdkcache.dto
      group-id: auth-cache-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  profiles:
    active: local
  application:
    name: "@project.artifactId@"
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
  datasource:
    url: jdbc:mysql://localhost:3306/app_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: app_user
    password: app_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET SESSION group_concat_max_len = 2097152

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false

main:
  log-startup-info: false # Opcional: remove as linhas "Starting..." e "No active profile..."
  banner-mode: "off"      # Opcional: remove o desenho do Spring

audit:
  product: "Portal Manager"
  origin: "@project.artifactId@"